<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Features;

class FeaturesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Tour Includes - only what is typically included, no ambiguous or duplicate items
        $tourIncludes = [
            ['name' => 'Accommodation', 'icon' => 'mdi-hotel', 'type' => 'include'],
            ['name' => 'Meals', 'icon' => 'mdi-food', 'type' => 'include'],
            ['name' => 'Breakfast', 'icon' => 'mdi-food-croissant', 'type' => 'include'],
            ['name' => 'Lunch', 'icon' => 'mdi-food-variant', 'type' => 'include'],
            ['name' => 'Dinner', 'icon' => 'mdi-food-steak', 'type' => 'include'],
            ['name' => 'Snacks', 'icon' => 'mdi-food-apple', 'type' => 'include'],
            ['name' => 'Beverages', 'icon' => 'mdi-coffee', 'type' => 'include'],
            ['name' => 'Transport', 'icon' => 'mdi-bus', 'type' => 'include'],
            ['name' => 'Guide', 'icon' => 'mdi-account-tie', 'type' => 'include'],
            ['name' => 'Entrance Fees', 'icon' => 'mdi-ticket-confirmation', 'type' => 'include'],
            ['name' => 'Airport Transfer', 'icon' => 'mdi-airplane', 'type' => 'include'],
            ['name' => 'Activities', 'icon' => 'mdi-gamepad-variant', 'type' => 'include'],
            ['name' => 'Equipment', 'icon' => 'mdi-tools', 'type' => 'include'],
            ['name' => 'Local SIM Card', 'icon' => 'mdi-sim', 'type' => 'include'],
            ['name' => 'Welcome Drink', 'icon' => 'mdi-glass-cocktail', 'type' => 'include'],
            ['name' => 'City Map', 'icon' => 'mdi-map', 'type' => 'include'],
            ['name' => 'Bottled Water', 'icon' => 'mdi-bottle-soda', 'type' => 'include'],
            ['name' => 'First Aid Kit', 'icon' => 'mdi-medical-bag', 'type' => 'include'],
            ['name' => 'WiFi On Board', 'icon' => 'mdi-wifi', 'type' => 'include'],
            ['name' => 'Photo Service', 'icon' => 'mdi-camera', 'type' => 'include'],
            ['name' => 'Porter Service', 'icon' => 'mdi-human-wheelchair', 'type' => 'include'],
            ['name' => 'Local Taxes', 'icon' => 'mdi-cash-multiple', 'type' => 'include'],
            ['name' => 'Workshops', 'icon' => 'mdi-school', 'type' => 'include'],
            ['name' => 'Boat Ride', 'icon' => 'mdi-ferry', 'type' => 'include'],
            ['name' => 'Train Tickets', 'icon' => 'mdi-train', 'type' => 'include'],
            ['name' => 'Bike Rental', 'icon' => 'mdi-bike', 'type' => 'include'],
            ['name' => 'Helmets', 'icon' => 'mdi-helmet', 'type' => 'include'],
            ['name' => 'Local Experiences', 'icon' => 'mdi-account-group', 'type' => 'include'],
            ['name' => 'Cultural Shows', 'icon' => 'mdi-drama-masks', 'type' => 'include'],
            ['name' => 'Cooking Class', 'icon' => 'mdi-pot-mix', 'type' => 'include'],
            ['name' => 'Language Support', 'icon' => 'mdi-translate', 'type' => 'include'],
            ['name' => 'Child Seat', 'icon' => 'mdi-seat-child', 'type' => 'include'],
            ['name' => 'Wheelchair Access', 'icon' => 'mdi-wheelchair-accessibility', 'type' => 'include'],
        ];

        // Tour Excludes - only what is typically excluded, and also includes some items that may be in both
        $tourExcludes = [
            ['name' => 'Personal Expenses', 'icon' => 'mdi-cash', 'type' => 'exclude'],
            ['name' => 'Travel Insurance', 'icon' => 'mdi-shield-account', 'type' => 'exclude'],
            ['name' => 'Visa Fees', 'icon' => 'mdi-passport', 'type' => 'exclude'],
            ['name' => 'Tips', 'icon' => 'mdi-currency-usd', 'type' => 'exclude'],
            ['name' => 'Alcoholic Beverages', 'icon' => 'mdi-glass-cocktail', 'type' => 'exclude'],
            ['name' => 'Optional Activities', 'icon' => 'mdi-star', 'type' => 'exclude'],
            ['name' => 'International Flights', 'icon' => 'mdi-airplane', 'type' => 'exclude'],
            ['name' => 'Personal Items', 'icon' => 'mdi-bag-personal', 'type' => 'exclude'],
            ['name' => 'Laundry Service', 'icon' => 'mdi-washing-machine', 'type' => 'exclude'],
            ['name' => 'Phone Calls', 'icon' => 'mdi-phone', 'type' => 'exclude'],
            ['name' => 'Room Service', 'icon' => 'mdi-room-service', 'type' => 'exclude'],
            ['name' => 'Mini Bar', 'icon' => 'mdi-glass-wine', 'type' => 'exclude'],
            ['name' => 'Medical Expenses', 'icon' => 'mdi-hospital', 'type' => 'exclude'],
            ['name' => 'Souvenirs', 'icon' => 'mdi-gift', 'type' => 'exclude'],
            ['name' => 'Excess Baggage', 'icon' => 'mdi-bag-suitcase', 'type' => 'exclude'],
            ['name' => 'Vaccinations', 'icon' => 'mdi-syringe', 'type' => 'exclude'],
            ['name' => 'Meals Not Mentioned', 'icon' => 'mdi-food-off', 'type' => 'exclude'],
            ['name' => 'Hotel Incidentals', 'icon' => 'mdi-hotel', 'type' => 'exclude'],
            ['name' => 'Late Checkout', 'icon' => 'mdi-clock-alert', 'type' => 'exclude'],
            ['name' => 'Early Check-in', 'icon' => 'mdi-clock-fast', 'type' => 'exclude'],
            ['name' => 'Extra Night', 'icon' => 'mdi-moon-waning-crescent', 'type' => 'exclude'],
            ['name' => 'Lost Items', 'icon' => 'mdi-magnify', 'type' => 'exclude'],
            ['name' => 'Damage Fees', 'icon' => 'mdi-hammer-wrench', 'type' => 'exclude'],
            ['name' => 'Porter Service', 'icon' => 'mdi-human-wheelchair', 'type' => 'exclude'],
            ['name' => 'Gratuities', 'icon' => 'mdi-currency-usd', 'type' => 'exclude'],
            ['name' => 'Unspecified Transfers', 'icon' => 'mdi-taxi', 'type' => 'exclude'],
            ['name' => 'Internet Charges', 'icon' => 'mdi-wifi-off', 'type' => 'exclude'],
            ['name' => 'Parking Fees', 'icon' => 'mdi-parking', 'type' => 'exclude'],
            ['name' => 'Toll Fees', 'icon' => 'mdi-road-variant', 'type' => 'exclude'],
            ['name' => 'Baggage Handling', 'icon' => 'mdi-bag-suitcase', 'type' => 'exclude'],
            ['name' => 'Insurance', 'icon' => 'mdi-shield', 'type' => 'exclude'],
            ['name' => 'Meals Not Included', 'icon' => 'mdi-food-off', 'type' => 'exclude'],
            ['name' => 'Drinks Not Included', 'icon' => 'mdi-glass-cocktail', 'type' => 'exclude'],
            ['name' => 'Personal Care Items', 'icon' => 'mdi-toothbrush-paste', 'type' => 'exclude'],
            // Some items that can be both included or excluded depending on the package
            ['name' => 'Laundry', 'icon' => 'mdi-washing-machine', 'type' => 'exclude'],
            ['name' => 'Accommodation', 'icon' => 'mdi-hotel', 'type' => 'include'],
            ['name' => 'Dinner', 'icon' => 'mdi-food-steak', 'type' => 'include'],
            ['name' => 'Breakfast', 'icon' => 'mdi-food-croissant', 'type' => 'include'],
            ['name' => 'Lunch', 'icon' => 'mdi-food-variant', 'type' => 'include'],
            ['name' => 'Snacks', 'icon' => 'mdi-food-apple', 'type' => 'include'],
            ['name' => 'Beverages', 'icon' => 'mdi-coffee', 'type' => 'include'],
            ['name' => 'Transport', 'icon' => 'mdi-bus', 'type' => 'include'],
            ['name' => 'Guide', 'icon' => 'mdi-account-tie', 'type' => 'include'],
            ['name' => 'Entrance Fees', 'icon' => 'mdi-ticket-confirmation', 'type' => 'include'],
            ['name' => 'Airport Transfer', 'icon' => 'mdi-airplane', 'type' => 'include'],
            ['name' => 'Activities', 'icon' => 'mdi-gamepad-variant', 'type' => 'include'],
            ['name' => 'Equipment', 'icon' => 'mdi-tools', 'type' => 'include'],
            ['name' => 'Local SIM Card', 'icon' => 'mdi-sim', 'type' => 'include'],
            ['name' => 'Welcome Drink', 'icon' => 'mdi-glass-cocktail', 'type' => 'include'],
            ['name' => 'City Map', 'icon' => 'mdi-map', 'type' => 'include'],
        ];

        $hotelFeatures = [
            ['name' => 'Free WiFi', 'icon' => 'mdi-wifi', 'type' => 'hotel'],
            ['name' => 'Swimming Pool', 'icon' => 'mdi-pool', 'type' => 'hotel'],
            ['name' => 'Fitness Center', 'icon' => 'mdi-dumbbell', 'type' => 'hotel'],
            ['name' => 'Restaurant', 'icon' => 'mdi-food', 'type' => 'hotel'],
            ['name' => 'Room Service', 'icon' => 'mdi-room-service', 'type' => 'hotel'],
            ['name' => 'Parking', 'icon' => 'mdi-parking', 'type' => 'hotel'],
            ['name' => 'Spa', 'icon' => 'mdi-spa', 'type' => 'hotel'],
            ['name' => 'Business Center', 'icon' => 'mdi-office-building', 'type' => 'hotel'],
            ['name' => 'Bar', 'icon' => 'mdi-glass-cocktail', 'type' => 'hotel'],
            ['name' => '24h Reception', 'icon' => 'mdi-clock', 'type' => 'hotel'],
            ['name' => 'Laundry Service', 'icon' => 'mdi-washing-machine', 'type' => 'hotel'],
            ['name' => 'Concierge', 'icon' => 'mdi-account-tie', 'type' => 'hotel'],
            ['name' => 'Elevator', 'icon' => 'mdi-elevator', 'type' => 'hotel'],
            ['name' => 'Pet Friendly', 'icon' => 'mdi-paw', 'type' => 'hotel'],
            ['name' => 'Non-smoking Rooms', 'icon' => 'mdi-smoking-off', 'type' => 'hotel'],
            ['name' => 'Family Rooms', 'icon' => 'mdi-account-group', 'type' => 'hotel'],
            ['name' => 'Airport Shuttle', 'icon' => 'mdi-airplane', 'type' => 'hotel'],
            ['name' => 'Luggage Storage', 'icon' => 'mdi-bag-suitcase', 'type' => 'hotel'],
            ['name' => 'Breakfast Included', 'icon' => 'mdi-food-croissant', 'type' => 'hotel'],
            ['name' => 'Minibar', 'icon' => 'mdi-glass-wine', 'type' => 'hotel'],
            ['name' => 'Safe Box', 'icon' => 'mdi-lock', 'type' => 'hotel'],
            ['name' => 'TV', 'icon' => 'mdi-television', 'type' => 'hotel'],
            ['name' => 'Air Conditioning', 'icon' => 'mdi-air-conditioner', 'type' => 'hotel'],
            ['name' => 'Heating', 'icon' => 'mdi-radiator', 'type' => 'hotel'],
            ['name' => 'Terrace', 'icon' => 'mdi-terrace', 'type' => 'hotel'],
            ['name' => 'Garden', 'icon' => 'mdi-flower', 'type' => 'hotel'],
            ['name' => 'Sauna', 'icon' => 'mdi-sauna', 'type' => 'hotel'],
            ['name' => 'Jacuzzi', 'icon' => 'mdi-hot-tub', 'type' => 'hotel'],
            ['name' => 'Massage', 'icon' => 'mdi-hand-heart', 'type' => 'hotel'],
            ['name' => 'Shuttle Service', 'icon' => 'mdi-taxi', 'type' => 'hotel'],
            ['name' => 'Wheelchair Access', 'icon' => 'mdi-wheelchair-accessibility', 'type' => 'hotel'],
            ['name' => 'Coffee/Tea Maker', 'icon' => 'mdi-coffee', 'type' => 'hotel'],
            ['name' => 'Iron', 'icon' => 'mdi-iron', 'type' => 'hotel'],
            ['name' => 'Hair Dryer', 'icon' => 'mdi-hair-dryer', 'type' => 'hotel'],
            ['name' => 'Bathrobe', 'icon' => 'mdi-tshirt-crew', 'type' => 'hotel'],
            ['name' => 'Toiletries', 'icon' => 'mdi-toothbrush-paste', 'type' => 'hotel'],
            ['name' => 'Soundproof Rooms', 'icon' => 'mdi-ear-hearing-off', 'type' => 'hotel'],
            ['name' => 'Fireplace', 'icon' => 'mdi-fireplace', 'type' => 'hotel'],
        ];

        $carFeatures = [
            ['name' => 'Air Conditioning', 'icon' => 'mdi-air-conditioner', 'type' => 'car'],
            ['name' => 'GPS Navigation', 'icon' => 'mdi-map-marker', 'type' => 'car'],
            ['name' => 'Bluetooth', 'icon' => 'mdi-bluetooth', 'type' => 'car'],
            ['name' => 'USB Charging', 'icon' => 'mdi-usb', 'type' => 'car'],
            ['name' => 'Backup Camera', 'icon' => 'mdi-camera', 'type' => 'car'],
            ['name' => 'Leather Seats', 'icon' => 'mdi-seat', 'type' => 'car'],
            ['name' => 'Sunroof', 'icon' => 'mdi-car-convertible', 'type' => 'car'],
            ['name' => 'Automatic Transmission', 'icon' => 'mdi-cog', 'type' => 'car'],
            ['name' => 'Manual Transmission', 'icon' => 'mdi-cog-outline', 'type' => 'car'],
            ['name' => 'Heated Seats', 'icon' => 'mdi-seat-recline-extra', 'type' => 'car'],
            ['name' => 'Cruise Control', 'icon' => 'mdi-speedometer', 'type' => 'car'],
            ['name' => 'Parking Sensors', 'icon' => 'mdi-radar', 'type' => 'car'],
            ['name' => 'All Wheel Drive', 'icon' => 'mdi-car-4wd', 'type' => 'car'],
            ['name' => 'Child Seat', 'icon' => 'mdi-seat-child', 'type' => 'car'],
            ['name' => 'Roof Rack', 'icon' => 'mdi-car-roof-rack', 'type' => 'car'],
            ['name' => 'Tinted Windows', 'icon' => 'mdi-car-door', 'type' => 'car'],
            ['name' => 'Keyless Entry', 'icon' => 'mdi-key-wireless', 'type' => 'car'],
            ['name' => 'Alarm System', 'icon' => 'mdi-alarm-light', 'type' => 'car'],
            ['name' => 'Fog Lights', 'icon' => 'mdi-car-light-fog', 'type' => 'car'],
            ['name' => 'Spare Tire', 'icon' => 'mdi-tire', 'type' => 'car'],
            ['name' => 'First Aid Kit', 'icon' => 'mdi-medical-bag', 'type' => 'car'],
            ['name' => 'Fire Extinguisher', 'icon' => 'mdi-fire-extinguisher', 'type' => 'car'],
            ['name' => 'Bluetooth Audio', 'icon' => 'mdi-bluetooth-audio', 'type' => 'car'],
            ['name' => 'Apple CarPlay', 'icon' => 'mdi-apple', 'type' => 'car'],
            ['name' => 'Android Auto', 'icon' => 'mdi-android', 'type' => 'car'],
            ['name' => 'Power Windows', 'icon' => 'mdi-window-closed', 'type' => 'car'],
            ['name' => 'Power Steering', 'icon' => 'mdi-steering', 'type' => 'car'],
            ['name' => 'ABS', 'icon' => 'mdi-car-brake-abs', 'type' => 'car'],
            ['name' => 'Central Locking', 'icon' => 'mdi-lock', 'type' => 'car'],
            ['name' => 'Electric Mirrors', 'icon' => 'mdi-car-side', 'type' => 'car'],
            ['name' => 'Rear Wiper', 'icon' => 'mdi-wiper', 'type' => 'car'],
            ['name' => 'Cup Holders', 'icon' => 'mdi-cup', 'type' => 'car'],
            ['name' => 'Armrest', 'icon' => 'mdi-arm-flex', 'type' => 'car'],
            ['name' => 'Sunshade', 'icon' => 'mdi-weather-sunny', 'type' => 'car'],
            ['name' => 'Navigation System', 'icon' => 'mdi-navigation', 'type' => 'car'],
        ];

        $apartmentFeatures = [
            ['name' => 'Kitchen', 'icon' => 'mdi-silverware-fork-knife', 'type' => 'apartment'],
            ['name' => 'Washing Machine', 'icon' => 'mdi-washing-machine', 'type' => 'apartment'],
            ['name' => 'Balcony', 'icon' => 'mdi-balcony', 'type' => 'apartment'],
            ['name' => 'Air Conditioning', 'icon' => 'mdi-air-conditioner', 'type' => 'apartment'],
            ['name' => 'Heating', 'icon' => 'mdi-radiator', 'type' => 'apartment'],
            ['name' => 'Elevator', 'icon' => 'mdi-elevator', 'type' => 'apartment'],
            ['name' => 'Pet Friendly', 'icon' => 'mdi-paw', 'type' => 'apartment'],
            ['name' => 'Garden', 'icon' => 'mdi-flower', 'type' => 'apartment'],
            ['name' => 'Dishwasher', 'icon' => 'mdi-dishwasher', 'type' => 'apartment'],
            ['name' => 'Microwave', 'icon' => 'mdi-microwave', 'type' => 'apartment'],
            ['name' => 'Coffee Machine', 'icon' => 'mdi-coffee-maker', 'type' => 'apartment'],
            ['name' => 'TV', 'icon' => 'mdi-television', 'type' => 'apartment'],
            ['name' => 'WiFi', 'icon' => 'mdi-wifi', 'type' => 'apartment'],
            ['name' => 'Iron', 'icon' => 'mdi-iron', 'type' => 'apartment'],
            ['name' => 'Hair Dryer', 'icon' => 'mdi-hair-dryer', 'type' => 'apartment'],
            ['name' => 'Terrace', 'icon' => 'mdi-terrace', 'type' => 'apartment'],
            ['name' => 'Fireplace', 'icon' => 'mdi-fireplace', 'type' => 'apartment'],
            ['name' => 'Soundproof', 'icon' => 'mdi-ear-hearing-off', 'type' => 'apartment'],
            ['name' => 'Private Parking', 'icon' => 'mdi-parking', 'type' => 'apartment'],
            ['name' => 'Security System', 'icon' => 'mdi-shield-home', 'type' => 'apartment'],
            ['name' => 'Smoke Detector', 'icon' => 'mdi-smoke-detector', 'type' => 'apartment'],
            ['name' => 'Baby Cot', 'icon' => 'mdi-baby-bottle', 'type' => 'apartment'],
            ['name' => 'Towels', 'icon' => 'mdi-towel', 'type' => 'apartment'],
            ['name' => 'Bed Linen', 'icon' => 'mdi-bed', 'type' => 'apartment'],
            ['name' => 'Closet', 'icon' => 'mdi-wardrobe', 'type' => 'apartment'],
            ['name' => 'Desk', 'icon' => 'mdi-desk', 'type' => 'apartment'],
            ['name' => 'Dining Area', 'icon' => 'mdi-silverware', 'type' => 'apartment'],
            ['name' => 'Oven', 'icon' => 'mdi-stove', 'type' => 'apartment'],
            ['name' => 'Refrigerator', 'icon' => 'mdi-fridge', 'type' => 'apartment'],
            ['name' => 'Toiletries', 'icon' => 'mdi-toothbrush-paste', 'type' => 'apartment'],
            ['name' => 'Bathtub', 'icon' => 'mdi-bathtub', 'type' => 'apartment'],
            ['name' => 'Shower', 'icon' => 'mdi-shower', 'type' => 'apartment'],
            ['name' => 'Wheelchair Access', 'icon' => 'mdi-wheelchair-accessibility', 'type' => 'apartment'],
            ['name' => 'Safe Box', 'icon' => 'mdi-lock', 'type' => 'apartment'],
            ['name' => 'Balcony View', 'icon' => 'mdi-eye', 'type' => 'apartment'],
        ];

        // Combine all features
        $allFeatures = array_merge($tourIncludes, $tourExcludes, $hotelFeatures, $carFeatures, $apartmentFeatures);

        // Seed all features
        foreach ($allFeatures as $feature) {
            Features::create([
                'name' => $feature['name'],
                'icon' => $feature['icon'],
                'type' => $feature['type'],
                'status' => true
            ]);
        }
    }
}
