<?php

return [
    'mdi-wifi', 'mdi-wifi-off', 'mdi-pool', 'mdi-dumbbell', 'mdi-food', 'mdi-food-off',
    'mdi-food-croissant', 'mdi-food-variant', 'mdi-food-steak', 'mdi-food-apple',
    'mdi-room-service', 'mdi-parking', 'mdi-spa', 'mdi-office-building', 'mdi-glass-cocktail',
    'mdi-glass-wine', 'mdi-clock', 'mdi-clock-alert', 'mdi-clock-fast', 'mdi-washing-machine',
    'mdi-account-tie', 'mdi-elevator', 'mdi-paw', 'mdi-smoking-off', 'mdi-account-group',
    'mdi-airplane', 'mdi-bag-suitcase', 'mdi-bag-personal', 'mdi-lock', 'mdi-television',
    'mdi-air-conditioner', 'mdi-radiator', 'mdi-terrace', 'mdi-flower', 'mdi-sauna',
    'mdi-hot-tub', 'mdi-hand-heart', 'mdi-taxi', 'mdi-wheelchair-accessibility', 'mdi-coffee',
    'mdi-iron', 'mdi-hair-dryer', 'mdi-toothbrush-paste', 'mdi-ear-hearing-off', 'mdi-fireplace',
    'mdi-star', 'mdi-heart', 'mdi-shield', 'mdi-shield-account', 'mdi-passport', 'mdi-currency-usd',
    'mdi-phone', 'mdi-hospital', 'mdi-gift', 'mdi-syringe', 'mdi-magnify', 'mdi-hammer-wrench',
    'mdi-road-variant', 'mdi-bus', 'mdi-train', 'mdi-ferry', 'mdi-bike', 'mdi-car',
    'mdi-car-sports', 'mdi-car-estate', 'mdi-car-convertible', 'mdi-car-4wd', 'mdi-car-door',
    'mdi-car-side', 'mdi-car-brake-abs', 'mdi-car-light-fog', 'mdi-car-roof-rack', 'mdi-car-cog',
    'mdi-map', 'mdi-map-marker', 'mdi-compass', 'mdi-beach', 'mdi-palm-tree', 'mdi-weather-sunny',
    'mdi-umbrella-beach', 'mdi-camera', 'mdi-video', 'mdi-music', 'mdi-drama-masks', 'mdi-school',
    'mdi-book-open', 'mdi-translate', 'mdi-sim', 'mdi-bottle-soda', 'mdi-medical-bag', 'mdi-tools',
    'mdi-gamepad-variant', 'mdi-ticket-confirmation', 'mdi-ticket', 'mdi-bed', 'mdi-bed-king',
    'mdi-shower', 'mdi-bathtub', 'mdi-kitchen', 'mdi-fridge', 'mdi-silverware-fork-knife',
    'mdi-grill', 'mdi-cctv', 'mdi-bell', 'mdi-key', 'mdi-key-wireless', 'mdi-garage',
    'mdi-balcony', 'mdi-window-open', 'mdi-curtains', 'mdi-lamp', 'mdi-fan', 'mdi-snowflake',
    'mdi-fire', 'mdi-water', 'mdi-leaf', 'mdi-ev-station', 'mdi-gas-station', 'mdi-engine',
    'mdi-seat', 'mdi-seat-child', 'mdi-seat-recline-extra', 'mdi-baby-carriage', 'mdi-human-male-female-child',
    'mdi-human-wheelchair', 'mdi-palette', 'mdi-image', 'mdi-waves', 'mdi-hiking', 'mdi-walk',
    'mdi-run', 'mdi-run-fast', 'mdi-tent', 'mdi-binoculars', 'mdi-earth', 'mdi-flag',
    'mdi-handshake', 'mdi-cash', 'mdi-cash-multiple', 'mdi-credit-card', 'mdi-wallet',
    'mdi-tag', 'mdi-percent', 'mdi-sale', 'mdi-thumb-up', 'mdi-check-circle', 'mdi-alert-circle',
    'mdi-information', 'mdi-help-circle', 'mdi-bluetooth', 'mdi-bluetooth-audio', 'mdi-usb',
    'mdi-radar', 'mdi-speedometer', 'mdi-steering', 'mdi-wiper', 'mdi-tire', 'mdi-fire-extinguisher',
    'mdi-alarm-light', 'mdi-apple', 'mdi-android', 'mdi-cog', 'mdi-cog-outline', 'mdi-moon-waning-crescent',
    'mdi-city-variant-outline', 'mdi-home-city', 'mdi-home', 'mdi-home-outline', 'mdi-hotel',
    'mdi-store', 'mdi-storefront', 'mdi-cart', 'mdi-basket', 'mdi-briefcase', 'mdi-clipboard-check',
    'mdi-calendar', 'mdi-calendar-check', 'mdi-email', 'mdi-email-outline', 'mdi-message',
    'mdi-headset', 'mdi-account', 'mdi-account-multiple', 'mdi-account-supervisor', 'mdi-face-agent',
    'mdi-lifebuoy', 'mdi-anchor', 'mdi-sail-boat', 'mdi-ship-wheel', 'mdi-fish', 'mdi-tree',
    'mdi-pine-tree', 'mdi-cactus', 'mdi-butterfly', 'mdi-bird', 'mdi-dog', 'mdi-cat',
    'mdi-broom', 'mdi-vacuum', 'mdi-spray-bottle', 'mdi-hand-wash', 'mdi-water-pump', 'mdi-pipe',
    'mdi-lightning-bolt', 'mdi-power-plug', 'mdi-battery', 'mdi-solar-power', 'mdi-wind-turbine',
];
